### PR TITLE
Fixed work on Windows during resetting bg/fg color

### LINKED ISSUE #66: Bug during resetting fg/bg on windows.
I'm look into your test colortest.cpp and run it on windows7 on mingw64 6.3.0. It does not work properly.

Look at your test code:

```c++
	// Visual test for background colors
	std::cout 
	  << rang::control::forceColor << rang::bg::green
	  << "This text has green background." << rang::bg::reset << std::endl
	  << rang::bg::red << "This text has red background." << rang::bg::reset
	  << std::endl
```
...

```c++
	  // Visual test for foreground colors
	  << rang::fg::green << "This text has green color." << rang::fg::reset
	  << std::endl
	  << rang::fg::red << "This text has red color." << rang::fg::reset
	  << std::endl
```
When you doing rang::fg::reset or rang::bg::reset you pass 39-30 = 9 and 49-40 = 9 to your funcion:

```c++
	inline WORD reverseRGB(WORD rgb)
	{
		static const WORD rev[8] = { 0, 4, 2, 6, 1, 5, 3, 7 };
		return rev[rgb];
	}
```
and it returns some trash instead of correct 3 bit value. 
I'm change your functions to workaround this:

```c++
	inline void setWinAttribute(rang::bg col, WORD &state)
	{
		state &= 0xFF0F;
		if(col != rang::bg::reset)
			state |= reverseRGB(static_cast<WORD>(col) - 40) << 4;
	}

	inline void setWinAttribute(rang::fg col, WORD &state)
	{
		state &= 0xFFF0;
		if(col != rang::fg::reset)
			state |= reverseRGB(static_cast<WORD>(col) - 30);
		else
			state |= (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED);
	}
```
And it's fixed.

So. Default windows state is **7** (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED) for foreground color and **0** for background color **at most** cases.  
By the way you can store user default settings from `GetConsoleScreenBufferInfo` something like this:

```c++
            static WORD defaultAttributes = 0;
            if (!defaultAttributes)
            {
                CONSOLE_SCREEN_BUFFER_INFO info;
                if (!GetConsoleScreenBufferInfo(getConsoleHandle(), &info))
                    return;
                defaultAttributes = info.wAttributes;
            }
```
and than use fg/bg color bits from that variable instead of 7 and 0.

### PR DESCRIPTION
**Pull request by kingseva**
1. Fixed work on Windows during resetting bg/fg color, fixes #66 
2. Added support of Windows 10 ANSI terminal sequences
3. Code should be work on native windows terminals

### CODE REVIEW

**Comment by agauniyal** [comment]
@kingseva I was trying this on windows 7 VM but it doesn't seems to work there. The only thing I changed from your PR was removing versionHelper header file (because it complains not found) and removing associated `IsWindowsVersionOrGreater(10, 0, 0)` and placing in one turn `true` and in another turn `false` there. Here's attached screenshot -
gmgqenq - imgur

**Comment by agauniyal** [comment]
Also `GetVersion()` function is deprecated, as it says here - https://msdn.microsoft.com/en-us/library/windows/desktop/ms724439(v=vs.85).aspx

> [GetVersion may be altered or unavailable for releases after Windows 8.1. Instead, use the Version Helper functions]

should we be using this 🤔

**Comment by agauniyal** [comment]
And what is this magic number -
https://github.com/agauniyal/rang/pull/67/files#diff-b693a7ef75f2ef3fcc47ee406adb8397R201

Related somehow to - `dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;` ?

**Comment by kingseva** [comment]
GetVersion is exists on all Windows versions. It's required for checking version of old windows (<Windows Vista) that doesn't support ascii mode. I'm test binary on Windows XP and Windows 7. And it's works fine. Check that branch SetConsoleTextAttribute is called inside setColor after your changes. ENABLE_VIRTUAL_TERMINAL_PROCESSING is mode for consolas on windows 10 or highter to enable ASCII symbols like any VT in Linux. https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

**Comment by kingseva** [comment]
Magic number is tested on WIndows 10. It's required for compilers with frameworks that don't have new defines, for correct build.

**Comment by kingseva** [comment]
By the way, i can't reproduce bug in windows 7. It's just builds and works. 




rang-windows7-test1

**Comment by agauniyal** [comment]
Oops you're right @kingseva, it wasn't working for me because `colortest.cpp` was still including old version. Your changes are good and works 👍

**Comment by agauniyal** [comment]
@kingseva I had to remove `GetVersion()` again on latest commit because newest visual studio doesn't lets me compile the project otherwise :(. I took the iso from here - https://developer.microsoft.com/en-us/windows/downloads/virtual-machines and tested multiple times on it. But other than that, everything runs fine 👍

**Pull request merged**
