### PR TITLE
Fixed issue #14: avoid multiple pointer copies

### PR DESCRIPTION
**Pull request by AxelStrem**
Replaced global vars with inline functions, as proposed [here](http://stackoverflow.com/questions/39450809/avoiding-redefinition-of-variables-for-single-header).

User is now required to call `rang::init()` before changing stream buffers.

Modified `test.cpp` to comply with that last rule.

### CODE REVIEW

**Comment by AxelStrem** [comment]
How would you test it, besides obvious visual check, which is already present?
If you want to test the case with changed buffers, not calling `rang::init()` will lead to unwanted behavior, do you want to test for that?

**Comment by agauniyal** [comment]
Not for failing, but a test for passing. Neither calling `rang::init()` nor changing the buffers should still pass the test. This scenario will cover the normal use case where users don't have to call `rang::init()`.

**Comment by AxelStrem** [comment]
Oh, well I've only added `rang::init()` where it was necessary (1 time). Visual tests do rely on lazy initialization, admittedly they are not really testing anything, but again, how do you want to test that?

**Comment by agauniyal** [comment]
I'll merge this by today, slightly busy with some work.

**Pull request merged**
