### PR TITLE
Remove redundant isTerminal check

### PR DESCRIPTION
**Pull request by agauniyal**

### CODE REVIEW

**Comment by agauniyal** [comment]
@kingseva I thought about it too and especially this part -
> than in Mac/Linux will see ANSI ESC sequences in output, but in Windows will see nothing. Is it normal behaviour? Yes, if it's documented that winTerm mode affects only OS Windows.

and I agreed with the code. But someone tried this branch and reported he was using -
```cpp
setControlModel(control::force);
setWinTermMode(winTerm::Native);
```
only but still seeing random escape codes in windows. His argument was when he has specified `winTerm::Native` then why is he seeing escape codes and no way to turn them off so he placed `#ifdefs` on his user code again which I want to avoid since this library already does that. I think the problem is `setControlModel(control::force)` doesn't make sense for windows since it will always support colors(if not ansi then native is always present) and `setWinTermMode(winTerm::Native)` doesn't make sense for Linux. So I thought a bit about it and then chose to go the explicit route where by default both will have `Auto` values and if user wants, they can explicitly call both functions and change whatsoever they want. I'm planning on writing extensive documentation for rang as well where I'll mention about this thoroughly and then release the next version. Would that be sufficient for the user to make the decision?

Also I'll rewrite tests to take CI running as arguments and then merge this PR 👍

**Comment by agauniyal** [comment]
> Note that isTerminal returns static value. There is no overhead to calling this function many times. But it's assume that application never redirects stdout/stderr in runtime from terminal to other and than back again from other to terminal (99% applications do not doing this). We write all this statics in isTerminal/getConsoleHandle/supportsAnsi functions for reducing overhead of calling _isatty/GetStdHandle/isMsysPty to speedup Rang function calls.

There is one another benefit of doing so which we are getting for free -  thread safety! Since static initialization in c++11 and above states that
> If multiple threads attempt to initialize the same static local variable concurrently, the initialization occurs exactly once (similar behavior can be obtained for arbitrary functions with std::call_once).

**Comment by agauniyal** [comment]
@kingseva I am also confused about this code - https://github.com/agauniyal/rang/blob/next-release/include/rang.hpp#L324-L328

```cpp
if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE),&info)
                || GetConsoleScreenBufferInfo(GetStdHandle(STD_ERROR_HANDLE),&info))
    attrib = info.wAttributes;

SGR sgr     = { 0, 0, 0, 0, FALSE, FALSE };
sgr.fgColor = attrib & 0x0F;
sgr.bgColor = (attrib & 0xF0) >> 4;
return sgr;
```

is the if condition like -
```cpp
if(... || ...) {
    attrib = info.wAttributes;
}
SGR sgr     = { 0, 0, 0, 0, FALSE, FALSE };
sgr.fgColor = attrib & 0x0F;
sgr.bgColor = (attrib & 0xF0) >> 4;
return sgr;
```
OR
```cpp
if(... || ...) {
    attrib = info.wAttributes;
    SGR sgr     = { 0, 0, 0, 0, FALSE, FALSE };
    sgr.fgColor = attrib & 0x0F;
    sgr.bgColor = (attrib & 0xF0) >> 4;
    return sgr;
}
```

If it's the first one(which I presume it is), then it's working fine but if it's the second one then it would be executing later statements unconditionally. I'll add the braces in this PR after we clarify this 😄

**Comment by agauniyal** [comment]
@kingseva I am also confused about this code - https://github.com/agauniyal/rang/blob/next-release/include/rang.hpp#L324-L328

```cpp
if (GetConsoleScreenBufferInfo(GetStdHandle(STD_OUTPUT_HANDLE),&info)
                || GetConsoleScreenBufferInfo(GetStdHandle(STD_ERROR_HANDLE),&info))
    attrib = info.wAttributes;

SGR sgr     = { 0, 0, 0, 0, FALSE, FALSE };
sgr.fgColor = attrib & 0x0F;
sgr.bgColor = (attrib & 0xF0) >> 4;
return sgr;
```

is the if condition like -
```cpp
// 1
if(... || ...) {
    attrib = info.wAttributes;
}
SGR sgr     = { 0, 0, 0, 0, FALSE, FALSE };
sgr.fgColor = attrib & 0x0F;
sgr.bgColor = (attrib & 0xF0) >> 4;
return sgr;
```
OR
```cpp
// 2
if(... || ...) {
    attrib = info.wAttributes;
    SGR sgr     = { 0, 0, 0, 0, FALSE, FALSE };
    sgr.fgColor = attrib & 0x0F;
    sgr.bgColor = (attrib & 0xF0) >> 4;
    return sgr;
}
```

If it's the first one(which I presume it is), then it's working fine but if it's the second one then it would be executing later statements unconditionally. I'll add the braces in this PR after we clarify this 😄

**Comment by kingseva** [comment]
1 of course. 2 will not initialize return value if condition fails. In my style of code formating I'm not use braces for one-line code pieces inside if/for/while blocks. :rofl:

**Comment by agauniyal** [comment]
No worries, I copied this clang-format from some blog years ago and been using it for a while. Both style works for me 😁

**Comment by agauniyal** [comment]
Oops, you're right, I somehow missed that scenario. Reverted the changes to those functions.

**Comment by kingseva** [comment]
Well, it should be ok, but don't forget that visualTest.cpp doesn't work in CI because there is no ANSI output to non-terminal in control::force mode.

```
 setControlModel(control::force);
 setWinTermMode(winTerm::Ansi);
```
Functions should be setted from program arguments (argv) by CI call.

**Comment by agauniyal** [comment]
visualTest.cpp is for users, I've skipped it from CI 😄

**Comment by agauniyal** [comment]
visualTest.cpp is for users, I've skipped it from CI since colorTest.cpp already tests all possible combination in CI 😄

**Pull request merged**
