### PR TITLE
Added color test

### PR DESCRIPTION
**Pull request by zeokav**
I have added a visual test that on running shows all the colors and font styles. 
(I'm not sure how blink and reverse work because I don't see any difference but I have added them anyway)

### CODE REVIEW

**Comment by agauniyal** [comment]
They don't work for most terminal emulators 😆

**Comment by zeokav** [comment]
No wonder. I checked for typos multiple times. 😆 
Include the rang.hpp to the colortest folder when checking. I didn't want to keep a duplicate on the repo. 😄

**Comment by agauniyal** [comment]
Could you add this test executable in CMakeLists.txt too? Also I would suggest using the same directory level as other tests since we only have 3 at total.

**Comment by zeokav** [comment]
I have made changes in CMakeLists and the .travis.yml file. I'm not entirely sure if what I did is right because I'm new to this... But let me know!

**Comment by agauniyal** [comment]
Everything's good 👍 Thanks for the PR 😄

**Pull request merged**
