### PR TITLE
Remove use of std::atomics

### PR DESCRIPTION
**Pull request by agauniyal**
Originally we had fully threadsafe Linux only code but along the way I'm realizing most users need to synchronize text output by themselves(mutex over `cout`), hence removal of thread safe code.

### CODE REVIEW

**Comment by agauniyal** [comment]
Most of the changes are from clang-format doing its work 💁‍♂️

**Comment by kingseva** [comment]
Why? Users expected to syncronize IO operations for ostreams by self since ostreams is not thread safe and rang do not tries to make ostreams thread safe. It's use only overloading of operators <<. But now we want to remove thread safe code from setWinTermMode/setControlMode functions. Which is unnecessary, since it's works fine before. Why make things worse than they are?

**Comment by agauniyal** [comment]
@kingseva 
I can think of two scenarios -
1. Single threaded application: This is going to work fine with or without `std::atomics`.
2. Multithreaded application: The text will interleave and so can colors/attributes so you can end up showing wrong output(full of escape codes and nonsense text). To solve this users are going to put up a mutex over `cout`/`clog`/`cerr` statements to prevent such bug.

In neither of cases making `rang::control` or `rang::winTerm` atomic never helps and users usually call it in top of program which has nothing to do with output of program. Sample multithreaded program -

```cpp
#include <iostream>
#include <thread>
#include "rang.hpp"

int main() {
  const auto func = [] { std::cout << "Hello World!"; };
  rang::control(...);
  std::thread t1(func), t2(func);
  t1.join();
  t2.join();
}
```

Even if someone uses `rang::control(...)` inside one thread while writing output in another thread I don't see how removal of `std::atomics` is going to hurt? 🤔

**Comment by kingseva** [comment]
For example we can control output to console from another thread to turn on or turn off colors. And control thread do not use interleaved cout/cerr/clog etc (i.e. for example GUI control thread and console log thread). When we call setControlMode to enable colors in future output of console thread, then it can read this value during our writing in operator << , which is bad, and atomics is useful to avoid that.

**Comment by agauniyal** [comment]
Hmm lets stay with correctness over this minor perf loss 😬

**Pull request closed without merging**
