### PR TITLE
Add preliminary support for cursor operations

### PR DESCRIPTION
**Pull request by agauniyal**
An experiment to provide cursor control in rang.

### CODE REVIEW

**Comment by agauniyal** [comment]
Need to find a way to make this work for -
```
template <std::ostream &... os>
void init()
{
    (void) std::initializer_list<int>{ (os.setf(std::ios::unitbuf), 0)... };
}
```
`std::wcout/..` and family. I tried a few things here - https://godbolt.org/g/JATtv5 but was unsuccesful till now.

**Comment by kingseva** [comment]
Hello! Interesting feature.
I'm add a little bit corrections (see commit message). 
I'm think that API of rang may be more stict:
```c++
std::cout << rang::cursor::hide << std::endl;
```
Instead of 
```c++
std::cout << rang::cursor::hide() << std::endl;
```
Because user may suggest to write rang::cursor::hide, as we use rang::style::reset, etc, without notation of function call/object creation. What do you think?

If we want to use notation of function call than it can be for example looks like:
```c++
std::cout << rang::cursor::setVisible(false) << std::endl;
```

Also as I know we can't mix in one program wcout/cout etc in tests. http://www.cplusplus.com/reference/iostream/wcout/
I think tests should be compiled with _UNICODE/UNICODE to test wide streams.

I don't like to call init with os.setf(std::ios::unitbuf). If it's turns off bufferization than output can be very slow :thinking:

**Comment by agauniyal** [comment]
@kingseva there are other functions lying on my local disk which take parameters like - `cout << cursor::move(0, 0);` or `cout << cursor::clearLn(cls::full);`, that's why I want to keep the interface uniform and make all of them methods. `rang::cursor::move` won't be able to take parameters here :sweat_smile:. I agree with this - `std::cout << rang::cursor::setVisible(false) << std::endl;` and will make this change in next commit.

> Also as I know we can't mix in one program wcout/cout etc in tests. 

Hmm, I wasn't aware of this :thinking: Will making two different files for `cxxx` and `wxxx` work here?

> I don't like to call init with os.setf(std::ios::unitbuf). If it's turns off bufferization than output can be very slow

I'll write in docs about `init` method. Not calling `rang::init(...)` before using cursor operations gives verryyy wierd output because lots of text is buffered and outputted at once. For example if you want to show a single loading progress bar like -
```
Progress:  25% [##########------------------------------]
```
It won't show progress bar at all and give weird output at once because of all buffering and text not outputting at realtime. The sync b/w terminal effects and actual text is broken due to buffering.

**Comment by agauniyal** [comment]
I forgot to mention, we can also call `os.flush()` inside our cursor methods too, do you think that's a good idea compared to `init()` ? :thinking:

**Comment by kingseva** [comment]
> Hmm, I wasn't aware of this :thinking: Will making two different files for cxxx and wxxx work here?

Yes, but conditional compilation is standart (and easiest?) way (in Windows for example) to achieve goal of using wide/narrow version of application. I'm add a little bit changes to cursorTest.cpp for example. 

>I'll write in docs about init method. Not calling rang::init(...) before using cursor operations gives verryyy wierd output because lots of text is buffered and outputted at once.

I'm agree. But it should not be required to call this function on every program that use rang.  Recently I'm even use same progress bar with additional flushes and it works ok (It's implemented as rewrited last line of output using \b (backspace) ). Note that we can use only escape characters in C++ code defined by standart: http://www.eel.is/c++draft/lex.ccon#7

**Comment by kingseva** [comment]
> I forgot to mention, we can also call os.flush() inside our cursor methods too, do you think that's a good idea compared to init() ? :thinking:

Maybe. Because user can use one function that uses rang for example to output logo of library. And then he expected to use only standart output. But after calling implicitly init function all standart output will become slow. So I think if we need init function, we also need deinit function. If this function may be usable only for cursor handling, then it can be named like initCursorOperations / deInitCursorOperations, which can be more reasonable.

Buy the way i never needed to use cursor operations before :wink: And of course it's hard to implement  all features cross-platform.

**Pull request merged**
