### PR TITLE
Better CMake support

### PR DESCRIPTION
**Pull request by maddouri**
This PR builds on the work of @zethon in #92 and a template I used for [one of my projects](https://github.com/maddouri/dynalo)

* Basic package config file when installing the library
* New `CMakeLists.txt` for the tests
* CTest for `test/test.cpp`

Hopefully, this makes integrating rang in other package managers (such as [Hunter](https://github.com/ruslo/hunter) and [Vcpkg](https://github.com/Microsoft/vcpkg)) easier.

### CODE REVIEW

**Comment by maddouri** [comment]
Yes. It seems that, among other possible issues:

1. Travis has an old version of Python _(probably 3.4.0 since it's an Ubuntu 14.04 container)_
    https://travis-ci.org/agauniyal/rang/jobs/450311421
    ```
    ... Meson requires Python 3.5.0 or greater
    ```
1. On Appveyor, _(I assume... I've never used Meson)_ the wrong syntax is used in the build command
    https://ci.appveyor.com/project/agauniyal/rang/builds/20028787/job/4c2y5rt0fv71k8s4
    ```
    meson: error: argument --buildtype: invalid choice: '' (choose from 'plain', 'debug', 'debugoptimized', 'release', 'minsize', 'custom')
    ```

**Comment by HemilTheRebel** [comment]
Exactly

**Comment by agauniyal** [comment]
Yeah I'll need to setup CI once again, things keep breaking with meson + conan setup :/

**Comment by agauniyal** [comment]
@maddouri the CI should work now, you can commit empty changes or make some comment/changes to see it works. Apologies for acting so late :sweat_smile:

**Comment by agauniyal** [comment]
@maddouri thanks for your work and patience :+1:

**Comment by amirmasoudabdol** [comment]
May I suggest you pushing this as a minor update to the package? I think it's really important and the CMake file looks much better than the current one. This makes it much easier to integrate rang into other projects.

**Pull request merged**
