### PR TITLE
Feature: Unformatted Input

### PR DESCRIPTION
**Pull request by qbradq**
Note: This is work-in-progress code. There are things like printf statements and junk that are expected to be removed from the final commit. Also some things continue to be refactored between working commits.

### CODE REVIEW

**Comment by qbradq** [comment]
The missing std:: namespaces is a known problem and addressed in the current in-progress commit. At this time I am focusing on the POSIX system code. It will be at least another day before I can resume testing on Windows platforms.

**Comment by agauniyal** [comment]
There's slight difference b/w current Develop branch and the node you based your work on. You can edit/merge them later, just giving heads up - 

```
diff --git a/include/rang.hpp b/include/rang.hpp
index 6398929..b59cd74 100644
--- a/include/rang.hpp
+++ b/include/rang.hpp
@@ -89,7 +89,7 @@ enum class bgB {
 	gray    = 107
 };
 
-enum class control { autoColor = 0, forceColor = 1 };
+enum class control { offColor = 0, autoColor = 1, forceColor = 2 };
 
 
 namespace rang_implementation {
@@ -114,10 +114,10 @@ namespace rang_implementation {
 	}
 
 
-	inline std::atomic<bool> &isColorForced()
+	inline std::atomic<int> &controlValue()
 	{
-		static std::atomic<bool> flag(false);
-		return flag;
+		static std::atomic<int> value(1);
+		return value;
 	}
 
 
@@ -272,12 +272,17 @@ template <typename T>
 inline rang_implementation::enableStd<T> operator<<(
   std::ostream &os, T const value)
 {
-	std::streambuf const *osbuf = os.rdbuf();
-	return rang_implementation::isColorForced()
-	    || (rang_implementation::supportsColor()
-	    && rang_implementation::isTerminal(osbuf))
-	  ? rang_implementation::setColor(os, value)
-	  : os;
+	const int option = rang_implementation::controlValue();
+	switch (option) {
+		case 0: return os;
+		case 1:
+			return rang_implementation::supportsColor()
+			    && rang_implementation::isTerminal(os.rdbuf())
+			  ? rang_implementation::setColor(os, value)
+			  : os;
+		case 2: return rang_implementation::setColor(os, value);
+		default: return os;
+	}
 }
 
 
@@ -285,10 +290,12 @@ template <typename T>
 inline rang_implementation::enableControl<T> operator<<(
   std::ostream &os, T const value)
 {
-	if (value == rang::control::forceColor) {
-		rang_implementation::isColorForced() = true;
+	if (value == rang::control::offColor) {
+		rang_implementation::controlValue() = 0;
 	} else if (value == rang::control::autoColor) {
-		rang_implementation::isColorForced() = false;
+		rang_implementation::controlValue() = 1;
+	} else if (value == rang::control::forceColor) {
+		rang_implementation::controlValue() = 2;
 	}
 	return os;
 }
diff --git a/test/visualTest.cpp b/test/visualTest.cpp
index dac8ce9..4dd1ba0 100644
--- a/test/visualTest.cpp
+++ b/test/visualTest.cpp
@@ -3,9 +3,19 @@
 int main()
 {
 	std::cout << std::endl
-	          << rang::control::forceColor  // For appveyor terminal
-	          << rang::style::reset << rang::bg::green << rang::fg::gray
-	          << "If you're seeing green background, then rang works!"
-	          << rang::style::reset << std::endl;
+
+	          << rang::control::autoColor << rang::bg::blue << rang::fg::gray
+	          << "Default autoColor mode - can auto detect color capablities"
+	          << rang::fg::reset << rang::bg::reset << std::endl
+	          << rang::control::forceColor << rang::bg::green << rang::fg::gray
+	          << "Forced color mode - if you see colored text then rang works!"
+	          << rang::fg::reset << rang::bg::reset << std::endl
+	          << rang::control::offColor << rang::fg::red << rang::bg::gray
+	          << rang::style::crossed
+	          << "No colors/attributes should be visible on this text."
+	          << rang::fg::reset << rang::bg::reset << rang::style::reset
+
+	          << std::endl;
+
 	return 0;
 }

```

**Comment by agauniyal** [comment]
we can also put scripts like `for x in {1..12}; do echo -n "F$x : "; tput kf$x | cat -A; echo; done` inside docs so that user could output his/her term info quickly for debug purposes. The above script produces output like -
```
F1 : ^[OP
F2 : ^[OQ
F3 : ^[OR
F4 : ^[OS
F5 : ^[[15~
F6 : ^[[17~
F7 : ^[[18~
F8 : ^[[19~
F9 : ^[[20~
F10 : ^[[21~
F11 : ^[[23~
F12 : ^[[24~
```

**Comment by qbradq** [comment]
Do we really want to use int controlValue() ? There's quite a few control options now with the input handling. Using a bitfield just seems... old school. Maybe rename it to outputControlValue() ? But even then we'll have more output control options in the future like local input echo.

**Comment by agauniyal** [comment]
`controlValue()` function is inside the current `develop` branch, you can do whatever seems right to you in your PR. I was just mentioning the current state of `develop` branch which includes the `offColor` option as well.

**Comment by agauniyal** [comment]
Script for the purpose I mentioned above -
```bash
#!/bin/sh

echo
for x in {1..12}; do echo -n "F$x : "; tput kf$x | cat -A; echo; done
echo

echo -n "Left  : "; tput kcub1 | cat -A; echo;
echo -n "Right : "; tput kcuf1 | cat -A; echo;
echo -n "Up    : "; tput kcuu1 | cat -A; echo;
echo -n "Down  : "; tput kcud1 | cat -A; echo;

echo

echo -n "Delete    : "; tput kdch1 | cat -A; echo;
echo -n "Home      : "; tput khome | cat -A; echo;
echo -n "End       : "; tput kend | cat -A; echo;
echo -n "Enter     : "; tput kent | cat -A; echo;
echo -n "Backspace : "; tput kbs | cat -A; echo;
```

produces output like -
```
F1 : ^[OP
F2 : ^[OQ
F3 : ^[OR
F4 : ^[OS
F5 : ^[[15~
F6 : ^[[17~
F7 : ^[[18~
F8 : ^[[19~
F9 : ^[[20~
F10 : ^[[21~
F11 : ^[[23~
F12 : ^[[24~

Left  : ^[OD
Right : ^[OC
Up    : ^[OA
Down  : ^[OB

Delete    : ^[[3~
Home      : ^[OH
End       : ^[OF
Enter     : ^[OM
Backspace : ^H
```

Links:
- https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html#SEC8
- http://linuxcommand.org/lc3_adv_tput.php

**Comment by qbradq** [comment]
Awesome script! I will include that in a tools directory. It beats what I have been doing :)

**Comment by agauniyal** [comment]
After a while you can also add your new test executables under previous ones to `.travis.yml` and appveyor config so that they show up in CI builds too. Feel free to ignore them during initial development phase.

**Comment by qbradq** [comment]
I've merged current develop branch into this. Also the allInput test is an interactive test. It is driven by the user providing input. I'm not sure how we could automate these particular tests.

**Comment by qbradq** [comment]
MSVC and MinGW builds work great. The project does not build on Cygwin, however. fileno() does not appear to be part of the standard libc or the POSIX standard and is not available within Cygwin. When I tried to hack around that the Cygwin terminal pass-through made the unformatted input processing impossible, at least with the termio library. I am going to setup my Windows 10 VM now and finished this PR up. Thank you for letting me know why Windows 10 is being treated differently for output. This helps.

**Comment by agauniyal** [comment]
@qbradq it could build on Cygwin too but we will have to use `-std=gnu++11` dialect of c++. Not so sure if I should change it in build configuration.

**Comment by qbradq** [comment]
Just let me know if we ever want to officially support cygwin as a platform. I'll have to look into input handling. This is ready to review now.

Um... apparently I did a bad while squashing this? Now there's tons of junk showing up in the PR. I've read the GitHub articles on doing this like five times now. I must be missing something. Sorry if I've made a mess of things.

**Comment by agauniyal** [comment]
@qbradq  I took a quick look and it looks fine to me. Also `rang::init()` is only needed once and in fact, it can be skipped altogether when we aren't going to redirect `cout`/`cerr`'s internal buffer to anywhere else which is a rare case. I'll prepare proper docs in `docs` folder like you did so that pretty much everything is clear to someone who is not me :p

I'll be free in a couple of hours and will pull your branch and do a review after which we can merge this back into develop and start working on remaining features. Btw tests are very good 👌 .

**Comment by agauniyal** [comment]
Would you mind telling how do these work?
```cpp
bool isCharacter() { return which < 0x80000000; }
bool isAscii() { return which < 0x0000007F; }
bool isPrintable() { return which > ' ' && isCharacter(); }
bool isPrintableAscii() { return which > ' ' && isAscii(); }
bool isSpecial() { return which > 0x80000000; }
bool isEmpty() { return which == 0x80000000; }
```

and a little later in this code -
```
enum State { Normal, Escape, ANSI, Xterm, XtermTeens, XtermTwenties, HiXtermDone };
```
what are Normal, escape, ansi ... terms here? Would more be added to these in future or are they complete? I'm also thinking of writing a `terminfo` parser in a few days which will definitely help the output portion of this library, would it help here too?
You can check the information available in `terminfo` by executing `$ infocmp xterm` replacing `xterm` with any terminal eg `gnome`.

**Comment by qbradq** [comment]
The functions are for the client code to reason about the key that was captured.

```
rang::Key key;
std::cin >> key;
if (key.isCharacter()) {
  // Key is not a special key
}
if (key.isPrintable()) {
  // Key is a printable, possibly Unicode codepoint
}
if (key.isAscii()) {
  // Key is not a special key and is not Unicode
}
if (key.isPrintableAscii()) {
  // Key is a printable ASCII codepoint
}
if (key.isSpecial()) {
  // Key is a non-printable special key. Compare to Key::Which
  switch(key) {
  case rang::Key::Which::Escape:
    // Do stuff
  }
}
if (key.isEmpty()) {
  // No key was pressed. This happens in non-blocking mode only.
}
```

A client wouldn't use all of these methods all at once. The above code is less of an example and more of a guide.

The State enum is internal to the input parsing function for VT100 terminals. This is why it is defined within the function body. It should be complete. If we switch to terminfo parsing then the current method of parsing VT100 input would become obsolete. We would need to re-write the entire function.

I think this would be a positive change for the library so long as you define a set of supported terminal emulators and stick to those. One of the reasons ncurses is such a beast is that they still support very old hardware terminals. While this is certainly a good use case for ncurses it may not be appropriate for a modern C++11 library.

**Comment by agauniyal** [comment]
@qbradq apologies but I was asking about how those bitwise operations are working eg - `which < 0x80000000;` . And a parser for terminfo db wouldn't happen soon but while seeing already built parser, it seems it was a much easier way to progress this library further to most terminals. It would probably appear in release 4 while we are currently preparing for 3rd release only 😄 

> The State enum is internal to the input parsing function for VT100 terminals. ...  It should be complete.

What terminals or family of terminals is it supporting? I even tried searching for these bits `XtermTeens, XtermTwenties, HiXtermDone` over google but couldn't find anything to match the context 😕

**Comment by qbradq** [comment]
0x80000000 is hexadecimal notation. It is the smallest number with the 31st bit set. The UTF32 standard states that no codepoint shall ever have the 31st bit set. So I've made all of the special meaning values of which have that bit set. This ensures there will never be a collision between a special value and a valid Unicode code point.

The State enum does not apply to a standard. It represents the various possible states of the state machine that is local to that one invocation of the function. The enum is not visible outside of that one function. See [this example](https://godbolt.org/g/zfLvTF) for proof.

**Comment by agauniyal** [comment]
@qbradq I apologize for the inconvenience but I'll be busy for next 2-3 days and then I'll definitely review this PR. Merry Christman ⛄️

**Comment by qbradq** [comment]
No problem. I've got plenty to busy myself with :) Merry Christmas!

**Comment by agauniyal** [comment]
Some questions -

- I haven't yet ran into such a system but I'm curious what happens if system doesn't supports `uint32_t` type(since they are not mandatory by c++ spec)? The compile fails would be the right thing to do here but I'm concerned about incorrect type scenario.

- is the mutex inside `getTerminalControlMutex()` getting [shared](http://en.cppreference.com/w/cpp/thread/shared_mutex)?

- `isSpecial()` corresponds to - special characters like '$', '%' or something else?

- in line [703](https://github.com/agauniyal/rang/blob/9f41069b7ded417baf3cc7065c42d253038b647a/include/rang.hpp#L703) the function that handles colored output, what happens if first `rang::control::forceColor` case is executed and right after it `rang::control::offColor` case is executed? Before there was a single `int` named `controlValue` that handled 3 values, now there are 2 seperate `bool` which need to be handled separately.

- Please see the same for this [method](https://github.com/agauniyal/rang/blob/9f41069b7ded417baf3cc7065c42d253038b647a/include/rang.hpp#L725), which of them can co-exist with each other, like can `sInputBlocking() = true` and `rang_implementation::isInputLowLatency() = true` exist together?

- Difference b/w `lowLatency` and `normalLatency`, if possible could you give an example where a user would use which?

you could use `const` a few places but rest looks fine, I cannot test on windows for some time as setting up a machine would take a lot of time so @AxelStrem could you take a look at this. Testing on Linux in few hours.

**Comment by agauniyal** [comment]
Found nice windows VM images which are already setup with required tools - https://developer.microsoft.com/en-us/windows/downloads/virtual-machines, so testing on windows will be possible today.

**Comment by qbradq** [comment]
- Fixed width data types are part of the C++11 standard: [reference](http://en.cppreference.com/w/cpp/types/integer)
- This use case is not appropriate for shared_mutex. shared_mutex is for read / write scenarios. All terminal operations are essentially write operations as they change the state of the terminal subsystem.
- I suppose a better name for isSpecial() would be isFunctionKey() or isNonPrintableKey().
- offColor takes precedence over forceColor, as in previous versions.
- isInputLowLatency() only applies when isInputBlocking() == false.
- normalLatency should be appropriate for most use cases. It reduces CPU utilization used during input polling while still responding to non-blocking input as fast as the OS will allow it to. lowLatency returns to the caller instead of idling the thread. lowLatency is appropriate for applications with high CPU demands.

I am learning a lot about C++ recently. My personal code base now uses const and noexcept. I still do not understand constexpr though.

**Comment by agauniyal** [comment]
- Fixed width data types are optional even in c++11(the link says it - in green text), but most compilers support them so that's good.
- I would appreciate if isSpecial is replaced with what you suggested.
- Generally const only dictates that compiler should shout(loudly) if someone tries to change a value marked as `const` whereas `constexpr` is compile time constant value, eg `constexpr int a = 5` and then `someResult = 5 * a` will be replaced into `5 * 5` at compile time with no resolution of variable being done at runtime.

**Comment by agauniyal** [comment]
Terminfo database parser is taking shape here - https://github.com/agauniyal/termdb, with just testing and documentation remaining.

**Comment by qbradq** [comment]
@agauniyal I think I'll close this PR if that's alright with you. I think your termdb parser is probably the way to go anyhow, plus I've found much better ways of handling input if you are assuming ECMA-48 compliance.

**Comment by agauniyal** [comment]
Sure, I appreciate the work you've done on this PR and it is definitely going to be used as a reference when input methods make way into this repo 👍  . Hope we work together again 😄

**Pull request closed without merging**
