### PR TITLE
Add documentation for 3.0

### PR DESCRIPTION
**Pull request by agauniyal**

### CODE REVIEW

**Comment by kingseva** [comment]
Great documentation!

rang::bg::reset and rang::fg::reset should also work and affect bg/bgB, fg/fgB colours respectevly. So it's possible to reset foreground/background only, instead of resetting all style. On native windows terminals also works correctly. Win10 have vt100 compatible sequencies, and it should also [work](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) (39 and 49 codes respectevly). 
I'm think it should be added to documentation.

By the way, I'm wanted to add nobold/nounderline etc. support but I can't doing that, because Win10 ANSI Terminal not provide that. That's weird and not full vt100 compatible terminal.

**Comment by kingseva** [comment]
In old Win we can use bold conceal and reversed, Italic is not supported :smiley_cat: blink/underline is emulated throw increasing of background intensity (this is default behaviour on most ansi drivers for windows terminal).

**Comment by agauniyal** [comment]
Made changes to docs based on the recent input!
> We also should tell something about redirection of ostreams from/to cout/cerr/clog and check it out.
Do you mean like the redirection performed in test.cpp?
```
std::ofstream out("out.txt");
std::streambuf *coutbuf = std::cout.rdbuf();
std::cout.rdbuf(out.rdbuf());
```
Or something different than that?

And what should we tell to users about it 🤔 ? Another thing to note is, 99% users won't bother themselves with these redirections and the rest will know what to do themselves 😛

**Comment by kingseva** [comment]
Yes. Exactly after your code rang tried to call **isatty(fileno(stdout))** for cout and still assume that output is going to terminal instead of file. It means that redirection of rdbuf for cout/cerr/clog objects is not supported. I'm  agree that 99% users don't need it. 

But if someone is need it, he should know that correct redirection of stdout/stderr should be done throw freopen function before calling any rang functions. 

Finally I'm create example of allocating terminal in WinAPI GUI application if someone want it. 
[allocterminal.cpp](https://gist.github.com/kingseva/a918ec66079a9475f19642ec31276a21)

**Comment by agauniyal** [comment]
@kingseva Would adding this to readme be fine -

---
### Redirecting `cout`/`cerr`/`clog` rdbuf?

Rang doesn't interfere if you try to redirect `cout`/`cerr`/`clog` to somewhere else and leaves the decision to the library user. Make sure you've read this [conversation](https://github.com/agauniyal/rang/pull/77#issuecomment-360991652) and check out the example code [here](https://gist.github.com/kingseva/a918ec66079a9475f19642ec31276a21).

**Comment by kingseva** [comment]
Yeah it's better than nothing. :smile:

**Comment by kingseva** [comment]
Intersting that wcout/wcerr/wclog is not supported.

**Comment by agauniyal** [comment]
Should we support them? They look very similar to `cout` and family so I guess fix is trivial...

**Comment by kingseva** [comment]
> Should we support them? They look very similar to cout and family so I guess fix is trivial...

Well, for generic purposes yes. It's not hard to add support of basic streams. I'm create branch generic_streams that support that feature if it's still interested. 

[kingseva/rang/generic_streams](https://github.com/kingseva/rang/tree/generic_streams) 

Tested on MSVC and GCC for wcout/wcerr etc.

**Comment by agauniyal** [comment]
sure, I created https://github.com/agauniyal/rang/tree/version4 for further PRs 😬 , also going to implement some features from #51 as soon as I get some time 👍

**Comment by kingseva** [comment]
Nice! I have some ideas about #52 . How to store rang values and process them in ostreams.

**Comment by agauniyal** [comment]
It would've been a lot easier if windows native method never operated directly on the terminal(and gave strings like win10/unix). I have 0 ideas how to store them into some stream for using them later when user wants 🤔

**Comment by kingseva** [comment]
It's possible to override behavior of operator << only for stringstream/ostringstream and store all values to stringstream as pure ANSI Esc sequencies into regular std::[w]string. After that for regular operator << for basic_ostreams we can create method "fromAnsi". it's returned some type that applied as pure string of Ansi Esc sequencies for Unix like systems or _parsed_ if Windows Native terminal is used.

**Pull request merged**
