### PR TITLE
Use alignas in isMsysPty buffer, fixes #82

### LINKED ISSUE #82: Potential UB in isMsysPty function
At line - https://github.com/agauniyal/rang/blob/master/include/rang.hpp#L195

Relevant comments from slack chat -
> djarek
> don't know winapi at all, but that looks like straight UB

> kaboissonneault
> I don't know if that's UB. `GetFileInformationByHandleEx` will create a proper object in that location.
> But to be safe, I'd do the reinterpret_cast _after_ calling GetFileInformationByHandleEx with the buffer. Though now that I think about it, isn't `static_cast` sufficient ?

> glenfe
> @kaboissonneault No. What alignment is buffer guaranteed to have?

> kaboissonneault
> Okay, then `buffer` should be properly aligned

> glenfe
> If it's not properly aligned, it's UB.
> The only guarantees you have for `char buffer[100];` are that is aligned suitably for `char`s. If you want higher alignment value guarantees (because the `FILE_NAME_INFO` type has higher alignment requirements, you need to use `alignas` (or `std::aligned_storage`).

> std::malloc(), ::operator new(std::size_t), ::operator new(std::size_t, const std::no_throw_t&) can be used to obtain storage that is suitably aligned for all fundamental types. i.e. Up to alignof(std::max_align_t).
> char c[N]; doesn't have those guarantees

### PR DESCRIPTION
**Pull request by agauniyal**

### CODE REVIEW

**Comment by kingseva** [comment]
Now, i think it should be fixed.

[off-by-default-compiler-warnings-in-visual-c/](https://blogs.msdn.microsoft.com/vcblog/2010/12/14/off-by-default-compiler-warnings-in-visual-c/) As described in this article /Wall warnings is unusable and it turned off by default. Authors recomend to compile code with /W4 option. 

Rang compiles without any warnings with /W4. 

With compiling /Wall option there are two warnings: C4365 and C4061. It's like casting from int to byte/wotd and not all enums in switch/case is defined. It can be fixed but it doen't make any sence.

And again codecov hate new commits :warning: .

**Comment by agauniyal** [comment]
@kingseva Don't worry about disabling the warnings in code, I was just asking if those warnings were something serious or not! Found out that `/W4` is the good flag to adhere by. Also thankyou for submitting this fix, even I wasn't aware of this UB 😅

**Comment by agauniyal** [comment]
Ignore codecov as well, its stupid. I'll see a way to shut it off for minor coverage changes.

**Comment by agauniyal** [comment]
@kingseva operator new calls malloc inside and provides same [gurantees](http://en.cppreference.com/w/cpp/memory/new/operator_new) so won't it be better to use it instead of malloc 🤔

**Comment by kingseva** [comment]
I'm agree, but what happens if FILE_NAME_INFO will chaged in new version of _WIN32_WINNT. Redefining existing C WinAPI to use operaator new instead of malloc looks more horrible. Because it's C API, I'm think that using malloc is standart way to achieve a goal.

**Comment by kingseva** [comment]
I know that MS cannot change API without renaming functions or function arguments for backward compability reasons. So, redifined struct should work everywhere, but in this case it's defined only to use operator new instead of malloc. That struct is small (contains two fileds), in general way if it will contain 100 fields, I would never like to redefine it, so I'm tried to find proper way to use existing API. I guess, in general way I found it. https://www.geeksforgeeks.org/struct-hack/

**Comment by kingseva** [comment]
I also believe, since this is the standard way to use 'Struct Hack', the code will be easier to read and understand by anyone.

**Comment by agauniyal** [comment]
@kingseva can we avoid this mess alltogether by using https://msdn.microsoft.com/en-us/library/windows/desktop/aa364962%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 🤔 ? I'm just looking for safe alternatives here before merging this PR so that we get it right this time. And even though its a _potential UB_, I haven't seen anything wrong in the wild yet but still its better to be safe than sorry 😄

**Comment by kingseva** [comment]
@agauniyal Well, I'm check this function: http://rextester.com/VLRSY51393 
with flags VOLUME_NAME_NONE | FILE_NAME_OPENED it's returned in MSYS2 on WIndows10:

``` bash
The final path is: \msys-dd50a72ab4668b33-pty1-to-master
```

If you wish to cleanup code you can use this function :wink: But i don't know weather works this function or not on another Windows versions. I believe it should... :smiley: 

I'm to lazy to redo same working code many times :expressionless:
Yet another better solution is to check Windows version and support checking of PTY with previous versions of Windows (XP,2000) throw NtQueryObject function (from Vista it's deprecated but before... it's ok.). But i'm think nowadays no one who wants to use MSYS/Cygwin in Windows XP .

Optimizations to memory allocations is not sufficient here, because  isMsysPty called 2-3 times in all program execution.. when we check stdout by isTerminal and when we check supportsAnsi. After that, isTerminal and supportsAnsi returns it's holded static values.

**Comment by agauniyal** [comment]
@kingseva I'm not worried about the optimizations at all, it's just that another developer on cpplang slack pointed out that malloc again might have problem with this approach. I'm thinking of simplifying the function like this -
```cpp
inline bool isMsysPty(int fd) noexcept
{
    HANDLE h = reinterpret_cast<HANDLE>(_get_osfhandle(fd));
    if (h == INVALID_HANDLE_VALUE) {
        return false;
    }

    // Check that it's a pipe:
    if (GetFileType(h) != FILE_TYPE_PIPE) {
        return false;
    }

    TCHAR Path[MAX_PATH];
    const auto result = GetFinalPathNameByHandle( h, Path, MAX_PATH, VOLUME_NAME_NONE | FILE_NAME_OPENED );
    if(dwRet >= MAX_PATH) return false;

    // Check pipe name is template of
    // {"cygwin-","msys-"}XXXXXXXXXXXXXXX-ptyX-XX
    std::wstring name(Path, dwRet);
    if ((name.find(L"msys-") == std::wstring::npos
         && name.find(L"cygwin-") == std::wstring::npos)
        || name.find(L"-pty") == std::wstring::npos) {
        return false;
    }
    return true;
}
```

The thing I'm not clear about are, are we losing anything by not loading the function dynamically as we are doing in current code and will std::wstring work nicely with `TCHAR Path[BUFSIZE]`? Otherwise I think this code will avoid almost all UB problems and is supported till same as current function in code. What do you think about it?

**Comment by kingseva** [comment]
@agauniyal Yes, if we don't do dynamic function loading we lose support of Windows XP. This function is declared from Windows Vista as msdn said. When application starts loader checks that all staically imported functions is supported by system libraries, if something is missing than it fails to start.

**Comment by kingseva** [comment]
@agauniyal I don't believe that malloc can have same approach with alignment pitfails because it means that all dynamically created objects in C language is UB ;) http://en.cppreference.com/w/c/types/max_align_t

**Comment by agauniyal** [comment]
@kingseva no not talking about C, it's specific to C++. Let me quote the experts and standard here -

```cpp
auto pNameInfo = std::unique_ptr<FILE_NAME_INFO, decltype(&std::free)>(
        static_cast<FILE_NAME_INFO*>(std::malloc(sizeNameInfo)), &std::free);
```

> Note, that it's technically not enough to just allocate enough storage for a struct in order to use it in C++. So, using malloc is usually not what you want.

> malloc doesn't create an object, new does. So, even though you allocated enough memory, using it as if it's an object of that struct is UB.

> There is some exception for PODs so it's not UB for all structs. I think.

> No, no exception for anything. In order to use an object, it has to exist. malloc doesn't create an object.

> According to the standard, object has type, lifetime, storage and value.

> where is UB?
> The lack of an object.
> http://eel.is/c++draft/intro.object#1.sentence-3
> An object occupies a region of storage in its period of construction, throughout its lifetime, and in its period of destruction.
> You only have "region of storage".

> You're missing construction. There is no object.

```cpp
auto storage = ::operator new(sizeof(int)); // Acquire storage, no object.

auto int_ptr = new (storage) int(42); // Construction, object lifetime begins.
std::destroy_at(int_ptr); // Destruction, object lifetime ends.

auto int_ptr = new (storage) int(17); // New object, same storage.
std::destroy_at(int_ptr); // Destruction, no more object.

::operator delete(storage); // Deallocation of storage.
```
> If object lifetime was restricted to storage acquisition, storage reuse such as the above would not make sense. Not to mention deferring of object construction post-storage-acquisition.

**Comment by agauniyal** [comment]
@kingseva you can consider joining cpplang slack here - https://cpplang.now.sh/ . Even I wasn't aware of some quirks in the code and they helped by pointing them out 😁

**Comment by agauniyal** [comment]
I'm thinking of rewriting that function like -
```cpp
inline bool isMsysPty(int fd) noexcept
{
    using TString = std::basic_string<TCHAR>;
    HANDLE h = reinterpret_cast<HANDLE>(_get_osfhandle(fd));
    if (h == INVALID_HANDLE_VALUE) {
        return false;
    }
    if (GetFileType(h) != FILE_TYPE_PIPE) {
        return false;
    }
    TCHAR Path[MAX_PATH];
    const auto result = GetFinalPathNameByHandle( h, Path, MAX_PATH, VOLUME_NAME_NONE | FILE_NAME_OPENED );
    if(result >= MAX_PATH) return false;
    TString name(Path, result);
    if ((name.find(TString("msys-")) == std::basic_string<TCHAR>::npos
         && name.find(TString("cygwin-")) == std::basic_string<TCHAR>::npos)
        || name.find(TString("-pty")) == std::basic_string<TCHAR>::npos) {
        return false;
    }
    return true;
}
```
Note that I haven't written dynamic load code, which we can discuss about since these functions are supported since Vista and XP support has already been ended since [2014](https://www.microsoft.com/en-in/windowsforbusiness/end-of-xp-support). If someone wants then developer can patch the library manually. Maybe we can make this change in v4.0 and keep dynamic load in this version for now. What do you think @kingseva?

**Comment by kingseva** [comment]
No, if you really wants to use TCHAR then correct function should looks like http://rextester.com/SZOY65738 
Don't forget that you include PR #71 and users still use Windows XP in many countries. So, if you remove support of it, they just opens new issue.

I'm found some information about GetFinalPathNameByHandle, it's checks that path correct or not and produce errors but GetFileInformationByHandleEx is not produce errors if path is incorrect.
http://rextester.com/MZC30356
I'm also notice that some people told bad news:  https://www.codeproject.com/Articles/35202/GetFinalPathNameByHandle-API-Hangs
GetFinalPathNameByHandle is may sometimes hangs, instead of GetFileInformationByHandleEx.

I'm not using FILE_NAME_INFO struct in C++ right after it's allocated. it's just passing to "C" function GetFileInformationByHandleEx and this function produce initialization of output POD. It's "C" WinAPI code. It's impossible to use operator new to allocate this function since it uses 'Struct hack'. But even if I would to use this in C++ i would do memset call right after it's allocated, but it's not required here.Note that its impossible to use all C++ features in C API.

**Comment by kingseva** [comment]
If you ask some people on "slack" tell him about context where and how this struct is used, after it's allocated.

**Comment by agauniyal** [comment]
Revisiting this since someone has emailed me pointing this UB issue again 😩. 

> No, if you really wants to use TCHAR then correct function should looks like http://rextester.com/SZOY65738

I'm ready to change the PR to this code since it looks clean to me.

> I'm found some information about GetFinalPathNameByHandle, it's checks that path correct or not and produce errors but GetFileInformationByHandleEx is not produce errors if path is incorrect.

This should be a good thing for us, no? We should use `GetFinalPathNameByHandle` to get errors while `GetFileInformationByHandleEx` ignores them. Is `GetFinalPathNameByHandle` bad for us?

> I'm also notice that some people told bad news: https://www.codeproject.com/Articles/35202/GetFinalPathNameByHandle-API-Hangs GetFinalPathNameByHandle is may sometimes hangs, instead of GetFileInformationByHandleEx.

This article points to 2009, I think its safe to assume it got fixed in 7-8 years by now 😅 

Using `GetFinalPathNameByHandle` solve both UB and backward compatiblity(since it has same as `GetFileInformationByHandleEx`) for us. I think we should go with it. It is very possible that current code will never cause UB under msvc compiler on windows but other compilers(clang) are catching up again so we can't be sure of it. I'd like to get this done so we can focus on other features. What are your thoughts on this @kingseva?

**Comment by kingseva** [comment]
> What are your thoughts on this @kingseva?

I'm recently ask people in slack how to properly initialize collection of objects in raw memory. They accepted that std::uninitialized_fill is good solution to using that. So, I'm just added initialization by 'placement new' here and std::uninitialized_fill. 

But, as i said before it's not required here, because we pass pointer to function that should 'construct' POD object inside. Strictly speaking, if it will be non POD object than we should manually call destructors here after stopping using objects. I'l try to implement this idea using templates and RAII for common C++ objects: https://wandbox.org/permlink/PpLY9VnCLs1HBq2v

**Comment by kingseva** [comment]
If we still think that this code is ugly, we can assume that WinAPI will never changed for backward compability reasons :wink: . Then we can create struct for own purposes with accordings to language standarts, as in previous commit e68c6834e21857aedefce51991b54a412625a3e5 
http://rextester.com/UGI62002

Both solutions works fine. We should make decision what version will be merged to master.

**Pull request merged**
